In [1]:
import get_movie
import pandas as pd
import get_movie

In [2]:
homepage_movies = "Dune, Shang Chi, No Time To Die, tick,tick...BOOM, Last Night in SoHo, Free Guy"
movies_list = homepage_movies.split(", ")
movies = []
for movie in movies_list:
    movies.append(get_movie.get_movie_data(movie))

df = pd.DataFrame(movies)
df

Actor 2 not found in database!
[7.2809771]
No budget information for this movie yet
Actor 1 not found in database!
Actor 2 not found in database!
[5.32990835]
Actor 2 not found in database!
Writer not found in database!
[7.94593795]
No budget information for this movie yet
Director not found in database!
Writer not found in database!
[7.80843374]
Actor 2 not found in database!
Director not found in database!
[5.8468856]
Actor 2 not found in database!
[5.84641109]

,title,image_url,duration,year,rating,ratingCount,genres,actor_1,actor_2,director,writer,budget,income,predicted_rating
0,Dune,https://m.media-amazon.com/images/M/MV5BN2FjNm...,155,2021,8.2,341426,"Action, Adventure, Drama, Sci-Fi",Timothée Chalamet,Rebecca Ferguson,Denis Villeneuve,Jon Spaihts,165000000.0,367091988,7.3
1,Shang-Chi and the Legend of the Ten Rings,https://m.media-amazon.com/images/M/MV5BNTliYj...,132,2021,7.6,200898,"Action, Adventure, Fantasy, Sci-Fi",Simu Liu,Tony Chiu-Wai Leung,Destin Daniel Cretton,Dave Callaham,65000000.0,431334583,5.3
2,No Time to Die,https://m.media-amazon.com/images/M/MV5BYWQ2Nz...,163,2021,7.4,202561,"Action, Adventure, Thriller",Daniel Craig,Léa Seydoux,Cary Joji Fukunaga,Neal Purvis,250000000.0,734091693,7.9
3,"tick, tick...BOOM!",https://m.media-amazon.com/images/M/MV5BZmMyMm...,115,2021,7.9,8915,"Biography, Drama, Musical",Andrew Garfield,Alexandra Shipp,Lin-Manuel Miranda,Steven Levenson,65000000.0,53080,7.8
4,Last Night in Soho,https://m.media-amazon.com/images/M/MV5BZjgwZD...,116,2021,7.3,36436,"Drama, Horror, Mystery, Thriller",Thomasin McKenzie,Aimee Cassettari,Edgar Wright,Edgar Wright,43000000.0,19530355,5.8
5,Free Guy,https://m.media-amazon.com/images/M/MV5BOTY2Nz...,115,2021,7.2,210036,"Action, Adventure, Comedy, Fantasy, Sci-Fi",Ryan Reynolds,Jodie Comer,Shawn Levy,Matt Lieberman,120000000.0,331444250,5.8

In [3]:
df.to_csv("static/data/homescreen_movies.csv")

In [3]:
learning_df = pd.read_csv("static/data/learning_sample.csv")
learning_df[['avg_vote', 'budget']]

       avg_vote   budget
0           4.3   125000
1           2.5   400000
2           5.2        0
3           6.0   400000
4           5.1  3600000
...         ...      ...
10470       5.0        0
10471       6.6        0
10472       6.5        0
10473       7.7        0
10474       2.3   500000

[10475 rows x 2 columns]

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

def imdb_linear():

    learning_df = pd.read_csv("static/data/learning_sample.csv")

    model = LinearRegression()

    y=learning_df['avg_vote_round']
    X=learning_df[['year', 'lead_number', 'production_number', 'director_number', 'writer_number', 'budget', 'duration', '0_Action', '0_Adventure', '0_Animation',
        '0_Biography', '0_Comedy', '0_Crime', '0_Drama', '0_Family',
        '0_Fantasy', '0_History', '0_Horror', '0_Music', '0_Musical',
        '0_Mystery', '0_News', '0_Romance', '0_Sci-Fi', '0_Sport', '0_Thriller',
        '0_War', '0_Western']]

    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

    scaler = StandardScaler().fit(X_train)
    X_train_scaled = scaler.transform(X_train)

    model.fit(X_train, y_train)

    print(f'Training Score: {model.score(X_train_scaled, y_train)}')
    print(f'Testing Score: {model.score(X_test, y_test)}')

    from sklearn.ensemble import RandomForestClassifier
    clf = RandomForestClassifier(random_state=1, n_estimators=500).fit(X_train, y_train)
    print(f'Training Score: {clf.score(X_train, y_train)}')
    print(f'Testing Score: {clf.score(X_test, y_test)}')

    return model

model = imdb_linear()

Training Score: -165.8664791494539
Testing Score: 0.3031446440163297
Training Score: 1.0
Testing Score: 0.34975181366933944